//! Mailbox message wire schemas (audit: invitation payload wire schema).
//!
//! Mailbox items are JWE-encrypted point-to-point messages: the server
//! stores opaque bytes, so the JSON inside the JWE is a pure
//! client-to-client contract (snake_case, frozen v1). Two message types
//! share the envelope, distinguished by the `type` field:
//!
//! - **invitation** — `{ "space_id", "space_key" (standard base64),
//!   "ucan_chain" (UCAN strings), "metadata"? { "space_name"?,
//!   "inviter_display_name"?, "epoch"? } }`
//! - **revocation notice** — `{ "type": "revocation", "space_id", "epoch"? }`
//!
//! Unknown fields are rejected on both (frozen v1 — no client sends extra
//! fields; rejecting catches contract drift early). `space_key` must be
//! canonical standard base64 (`btoa`-style: alphabet + trailing padding,
//! length a multiple of 4) — tightened vs. the pre-port `atob` call, which
//! also accepted unpadded input.
//!
//! Conformance is pinned by `test-vectors/invitation-payload.json`
//! (generated by `examples/generate_invitation_vectors.rs`), replayed by
//! the Rust conformance test, the node 1:1 mirror, and the real-wasm
//! browser test.

use crate::js_numbers::number_js_safe_uint;
use serde::{Deserialize, Serialize};
use serde_json::Value;

/// Invitation payload field names in canonical order (frozen v1).
pub const INVITATION_PAYLOAD_FIELDS: &[&str] = &["space_id", "space_key", "ucan_chain", "metadata"];

/// Invitation `metadata` field names in canonical order (frozen v1).
pub const INVITATION_METADATA_FIELDS: &[&str] = &["space_name", "inviter_display_name", "epoch"];

/// Revocation notice field names in canonical order (frozen v1).
pub const REVOCATION_NOTICE_FIELDS: &[&str] = &["type", "space_id", "epoch"];

/// The `type` discriminator value for revocation notices (frozen v1).
pub const REVOCATION_NOTICE_TYPE: &str = "revocation";

#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
pub enum MailboxMessageError {
    #[error("{0}")]
    Invalid(String),
}

fn invalid(msg: &str) -> MailboxMessageError {
    MailboxMessageError::Invalid(msg.to_string())
}

/// Invitation metadata (all fields optional).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct InvitationMetadata {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub space_name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub inviter_display_name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub epoch: Option<i64>,
}

/// Invitation payload (the wire schema inside the JWE).
///
/// `space_key` is the raw space key as canonical standard base64.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct InvitationPayloadWire {
    pub space_id: String,
    pub space_key: String,
    pub ucan_chain: Vec<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub metadata: Option<InvitationMetadata>,
}

/// Revocation notice (the wire schema inside the JWE).
#[derive(Debug, Clone, PartialEq)]
pub struct RevocationNotice {
    pub space_id: String,
    pub epoch: Option<i64>,
}

/// A decoded mailbox message.
#[derive(Debug, Clone, PartialEq)]
pub enum MailboxMessage {
    Invitation(InvitationPayloadWire),
    Revocation(RevocationNotice),
}

/// Parse a mailbox message JWE plaintext (JSON).
///
/// Dispatch (frozen): an object with `type == "revocation"` is a
/// revocation notice; any other value (absent, `null`, non-string, other
/// string) is an invitation payload — where a present `type` field is an
/// unknown field and rejected.
pub fn parse_mailbox_message(json: &str) -> Result<MailboxMessage, MailboxMessageError> {
    let v: Value =
        serde_json::from_str(json).map_err(|_| invalid("mailbox message: invalid JSON"))?;
    let obj = v
        .as_object()
        .ok_or_else(|| invalid("mailbox message: must be a JSON object"))?;
    if obj.get("type").and_then(Value::as_str) == Some(REVOCATION_NOTICE_TYPE) {
        return parse_revocation_notice(obj).map(MailboxMessage::Revocation);
    }
    parse_invitation_payload(obj).map(MailboxMessage::Invitation)
}

/// Serialize an invitation payload to its canonical wire JSON (compact,
/// frozen field order: `space_id`, `space_key`, `ucan_chain`, `metadata`;
/// `metadata` omitted when absent, optional metadata fields omitted when
/// absent).
pub fn serialize_invitation_payload(payload: &InvitationPayloadWire) -> String {
    serde_json::to_string(payload).expect("InvitationPayloadWire always serializes")
}

fn parse_invitation_payload(
    obj: &serde_json::Map<String, Value>,
) -> Result<InvitationPayloadWire, MailboxMessageError> {
    reject_unknown_fields(obj, INVITATION_PAYLOAD_FIELDS, "invitation payload")?;
    for field in ["space_id", "space_key", "ucan_chain"] {
        if !obj.contains_key(field) {
            return Err(invalid(&format!(
                "invitation payload: missing required field '{field}'"
            )));
        }
    }

    let space_id = obj
        .get("space_id")
        .and_then(Value::as_str)
        .ok_or_else(|| invalid("invitation payload: field 'space_id' must be a string"))?
        .to_string();

    let space_key = obj
        .get("space_key")
        .and_then(Value::as_str)
        .ok_or_else(|| invalid("invitation payload: field 'space_key' must be a string"))?;
    if !is_canonical_base64(space_key) {
        return Err(invalid(
            "invitation payload: field 'space_key' is not valid base64",
        ));
    }
    let space_key = space_key.to_string();

    let chain = obj
        .get("ucan_chain")
        .and_then(Value::as_array)
        .ok_or_else(|| invalid("invitation payload: field 'ucan_chain' must be an array"))?;
    let mut ucan_chain = Vec::with_capacity(chain.len());
    for (i, ucan) in chain.iter().enumerate() {
        let s = ucan.as_str().ok_or_else(|| {
            invalid(&format!(
                "invitation payload: ucan_chain[{i}] must be a string"
            ))
        })?;
        ucan_chain.push(s.to_string());
    }

    let metadata = match obj.get("metadata") {
        None | Some(Value::Null) => None,
        Some(Value::Object(m)) => Some(parse_invitation_metadata(m)?),
        Some(_) => {
            return Err(invalid(
                "invitation payload: field 'metadata' must be an object",
            ))
        }
    };

    Ok(InvitationPayloadWire {
        space_id,
        space_key,
        ucan_chain,
        metadata,
    })
}

fn parse_invitation_metadata(
    obj: &serde_json::Map<String, Value>,
) -> Result<InvitationMetadata, MailboxMessageError> {
    reject_unknown_fields(
        obj,
        INVITATION_METADATA_FIELDS,
        "invitation payload: metadata",
    )?;
    Ok(InvitationMetadata {
        space_name: lenient_string(obj.get("space_name")),
        inviter_display_name: lenient_string(obj.get("inviter_display_name")),
        epoch: parse_optional_epoch(obj.get("epoch"), "invitation payload: metadata")?,
    })
}

fn parse_revocation_notice(
    obj: &serde_json::Map<String, Value>,
) -> Result<RevocationNotice, MailboxMessageError> {
    reject_unknown_fields(obj, REVOCATION_NOTICE_FIELDS, "revocation notice")?;
    let space_id = obj
        .get("space_id")
        .and_then(Value::as_str)
        .ok_or_else(|| invalid("revocation notice: field 'space_id' must be a string"))?
        .to_string();
    let epoch = parse_optional_epoch(obj.get("epoch"), "revocation notice")?;
    Ok(RevocationNotice { space_id, epoch })
}

/// Lenient optional string (same rule as `__spaces`): absent/null →
/// `None`, non-string → `None` (dropped), string → `Some`.
fn lenient_string(v: Option<&Value>) -> Option<String> {
    v.and_then(Value::as_str).map(|s| s.to_string())
}

/// Optional non-negative JS-safe integer field: absent/null → `None`,
/// present but non-integer → error (same rule as the `__spaces` counters).
fn parse_optional_epoch(
    v: Option<&Value>,
    prefix: &str,
) -> Result<Option<i64>, MailboxMessageError> {
    match v {
        None | Some(Value::Null) => Ok(None),
        Some(Value::Number(n)) => match number_js_safe_uint(n) {
            Some(u) => Ok(Some(u as i64)),
            None => Err(invalid(&format!(
                "{prefix}: field 'epoch' must be a non-negative integer"
            ))),
        },
        Some(_) => Err(invalid(&format!(
            "{prefix}: field 'epoch' must be a non-negative integer"
        ))),
    }
}

/// Reject unknown fields (sorted by code point; the first is reported) —
/// the frozen-schema rule shared with `__spaces`.
fn reject_unknown_fields(
    obj: &serde_json::Map<String, Value>,
    allowed: &[&str],
    prefix: &str,
) -> Result<(), MailboxMessageError> {
    let unknown: Vec<&String> = obj
        .keys()
        .filter(|k| !allowed.contains(&k.as_str()))
        .collect();
    let mut sorted = unknown;
    sorted.sort();
    if let Some(first) = sorted.first() {
        return Err(invalid(&format!("{prefix}: unknown field '{first}'")));
    }
    Ok(())
}

/// Canonical standard base64 (`btoa`-style): alphabet A-Z a-z 0-9 + /,
/// padding only in the final group, total length a multiple of 4.
///
/// Implemented with `base64ct`'s strict `standard::Base64` decoder: it
/// accepts exactly the canonical form (and rejects, e.g., unpadded input
/// that `atob` would accept).
fn is_canonical_base64(s: &str) -> bool {
    use base64ct::Encoding;
    base64ct::Base64::decode_vec(s).is_ok()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn expect_err(json: &str, expected: &str) {
        assert_eq!(
            parse_mailbox_message(json).unwrap_err().to_string(),
            expected,
            "for {json:?}"
        );
    }

    #[test]
    fn parses_invitation_payload() {
        let json = r#"{"space_id":"s1","space_key":"AQIDBA==","ucan_chain":["u1","u2"],"metadata":{"space_name":"Shared","epoch":3}}"#;
        let msg = parse_mailbox_message(json).unwrap();
        let p = match msg {
            MailboxMessage::Invitation(p) => p,
            MailboxMessage::Revocation(_) => panic!("expected invitation"),
        };
        assert_eq!(p.space_id, "s1");
        assert_eq!(p.space_key, "AQIDBA==");
        assert_eq!(p.ucan_chain, vec!["u1", "u2"]);
        assert_eq!(
            p.metadata,
            Some(InvitationMetadata {
                space_name: Some("Shared".into()),
                inviter_display_name: None,
                epoch: Some(3),
            })
        );
    }

    #[test]
    fn parses_revocation_notice() {
        let msg =
            parse_mailbox_message(r#"{"type":"revocation","space_id":"s1","epoch":2}"#).unwrap();
        let n = match msg {
            MailboxMessage::Revocation(n) => n,
            MailboxMessage::Invitation(_) => panic!("expected revocation"),
        };
        assert_eq!(n.space_id, "s1");
        assert_eq!(n.epoch, Some(2));

        let msg = parse_mailbox_message(r#"{"type":"revocation","space_id":"s1"}"#).unwrap();
        let n = match msg {
            MailboxMessage::Revocation(n) => n,
            MailboxMessage::Invitation(_) => panic!("expected revocation"),
        };
        assert_eq!(n.epoch, None);
    }

    #[test]
    fn dispatch_on_type_field() {
        // Absent type → invitation branch (missing required fields error).
        expect_err(
            r#"{}"#,
            "invitation payload: missing required field 'space_id'",
        );
        // Non-matching / non-string type → invitation branch, `type` is an
        // unknown field.
        for json in [
            r#"{"type":"weird","space_id":"s","space_key":"AQIDBA==","ucan_chain":[]}"#,
            r#"{"type":null,"space_id":"s","space_key":"AQIDBA==","ucan_chain":[]}"#,
            r#"{"type":5,"space_id":"s","space_key":"AQIDBA==","ucan_chain":[]}"#,
        ] {
            expect_err(json, "invitation payload: unknown field 'type'");
        }
    }

    #[test]
    fn invitation_errors() {
        expect_err(
            r#"{"space_key":"AQIDBA==","ucan_chain":[]}"#,
            "invitation payload: missing required field 'space_id'",
        );
        expect_err(
            r#"{"space_id":"s","ucan_chain":[]}"#,
            "invitation payload: missing required field 'space_key'",
        );
        expect_err(
            r#"{"space_id":"s","space_key":"AQIDBA=="}"#,
            "invitation payload: missing required field 'ucan_chain'",
        );
        expect_err(
            r#"{"space_id":5,"space_key":"AQIDBA==","ucan_chain":[]}"#,
            "invitation payload: field 'space_id' must be a string",
        );
        expect_err(
            r#"{"space_id":"s","space_key":5,"ucan_chain":[]}"#,
            "invitation payload: field 'space_key' must be a string",
        );
        expect_err(
            r#"{"space_id":"s","space_key":"abc","ucan_chain":[]}"#,
            "invitation payload: field 'space_key' is not valid base64",
        );
        expect_err(
            r#"{"space_id":"s","space_key":"!!!","ucan_chain":[]}"#,
            "invitation payload: field 'space_key' is not valid base64",
        );
        expect_err(
            r#"{"space_id":"s","space_key":"AQIDBA==","ucan_chain":"x"}"#,
            "invitation payload: field 'ucan_chain' must be an array",
        );
        expect_err(
            r#"{"space_id":"s","space_key":"AQIDBA==","ucan_chain":[1]}"#,
            "invitation payload: ucan_chain[0] must be a string",
        );
        expect_err(
            r#"{"space_id":"s","space_key":"AQIDBA==","ucan_chain":[],"metadata":5}"#,
            "invitation payload: field 'metadata' must be an object",
        );
        expect_err(
            r#"{"space_id":"s","space_key":"AQIDBA==","ucan_chain":[],"metadata":{"zzz":1}}"#,
            "invitation payload: metadata: unknown field 'zzz'",
        );
        expect_err(
            r#"{"space_id":"s","space_key":"AQIDBA==","ucan_chain":[],"metadata":{"epoch":-1}}"#,
            "invitation payload: metadata: field 'epoch' must be a non-negative integer",
        );
        expect_err(
            r#"{"space_id":"s","space_key":"AQIDBA==","ucan_chain":[],"metadata":{"epoch":1.5}}"#,
            "invitation payload: metadata: field 'epoch' must be a non-negative integer",
        );
        expect_err(
            r#"{"space_id":"s","space_key":"AQIDBA==","ucan_chain":[],"metadata":{"epoch":9007199254740992}}"#,
            "invitation payload: metadata: field 'epoch' must be a non-negative integer",
        );
        // Unknown fields are reported alphabetically, first wins.
        expect_err(
            r#"{"space_id":"s","space_key":"AQIDBA==","ucan_chain":[],"bbb":1,"aaa":2}"#,
            "invitation payload: unknown field 'aaa'",
        );
        // Lenient optional metadata values: non-string → dropped.
        let msg = parse_mailbox_message(
            r#"{"space_id":"s","space_key":"AQIDBA==","ucan_chain":[],"metadata":{"space_name":5,"inviter_display_name":null,"epoch":null}}"#,
        )
        .unwrap();
        let p = match msg {
            MailboxMessage::Invitation(p) => p,
            MailboxMessage::Revocation(_) => panic!("expected invitation"),
        };
        assert_eq!(
            p.metadata,
            Some(InvitationMetadata {
                space_name: None,
                inviter_display_name: None,
                epoch: None,
            })
        );
    }

    #[test]
    fn revocation_errors() {
        expect_err(
            r#"{"type":"revocation"}"#,
            "revocation notice: field 'space_id' must be a string",
        );
        expect_err(
            r#"{"type":"revocation","space_id":5}"#,
            "revocation notice: field 'space_id' must be a string",
        );
        expect_err(
            r#"{"type":"revocation","space_id":"s","epoch":-1}"#,
            "revocation notice: field 'epoch' must be a non-negative integer",
        );
        expect_err(
            r#"{"type":"revocation","space_id":"s","epoch":1.5}"#,
            "revocation notice: field 'epoch' must be a non-negative integer",
        );
        expect_err(
            r#"{"type":"revocation","space_id":"s","zzz":1}"#,
            "revocation notice: unknown field 'zzz'",
        );
    }

    #[test]
    fn invalid_json_and_non_objects() {
        expect_err("{nope", "mailbox message: invalid JSON");
        expect_err(r#""hello""#, "mailbox message: must be a JSON object");
        expect_err("5", "mailbox message: must be a JSON object");
        expect_err("null", "mailbox message: must be a JSON object");
        expect_err("true", "mailbox message: must be a JSON object");
        expect_err("[]", "mailbox message: must be a JSON object");
    }

    #[test]
    fn canonical_base64_rule() {
        for ok in ["", "AQ==", "AQI=", "AQID", "AQIDBA==", "abcd/EFg+IJK"] {
            assert!(is_canonical_base64(ok), "should accept {ok:?}");
        }
        for bad in [
            "abc", "A===", "ab=c", "a b=", "AQ!D", "AQID=", "====", "AQ==BA==",
        ] {
            assert!(!is_canonical_base64(bad), "should reject {bad:?}");
        }
    }

    #[test]
    fn serialization_roundtrip() {
        let p = InvitationPayloadWire {
            space_id: "s1".into(),
            space_key: "AQIDBA==".into(),
            ucan_chain: vec!["u1".into()],
            metadata: Some(InvitationMetadata {
                space_name: Some("Shared".into()),
                inviter_display_name: None,
                epoch: Some(3),
            }),
        };
        assert_eq!(
            serialize_invitation_payload(&p),
            r#"{"space_id":"s1","space_key":"AQIDBA==","ucan_chain":["u1"],"metadata":{"space_name":"Shared","epoch":3}}"#
        );
        let p2 = InvitationPayloadWire {
            space_id: "s2".into(),
            space_key: "AQID".into(),
            ucan_chain: vec![],
            metadata: None,
        };
        assert_eq!(
            serialize_invitation_payload(&p2),
            r#"{"space_id":"s2","space_key":"AQID","ucan_chain":[]}"#
        );
        // metadata present but empty stays present.
        let p3 = InvitationPayloadWire {
            space_id: "s3".into(),
            space_key: "AQID".into(),
            ucan_chain: vec![],
            metadata: Some(InvitationMetadata {
                space_name: None,
                inviter_display_name: None,
                epoch: None,
            }),
        };
        assert_eq!(
            serialize_invitation_payload(&p3),
            r#"{"space_id":"s3","space_key":"AQID","ucan_chain":[],"metadata":{}}"#
        );
    }

    #[test]
    fn conformance_vectors() {
        let json = include_str!("../test-vectors/invitation-payload.json");
        let v: Value = serde_json::from_str(json).unwrap();

        let fields: Vec<String> = v["invitationFields"]
            .as_array()
            .unwrap()
            .iter()
            .map(|f| f.as_str().unwrap().to_string())
            .collect();
        assert_eq!(
            fields,
            INVITATION_PAYLOAD_FIELDS
                .iter()
                .map(|f| f.to_string())
                .collect::<Vec<_>>()
        );
        let mfields: Vec<String> = v["metadataFields"]
            .as_array()
            .unwrap()
            .iter()
            .map(|f| f.as_str().unwrap().to_string())
            .collect();
        assert_eq!(
            mfields,
            INVITATION_METADATA_FIELDS
                .iter()
                .map(|f| f.to_string())
                .collect::<Vec<_>>()
        );
        let rfields: Vec<String> = v["revocationFields"]
            .as_array()
            .unwrap()
            .iter()
            .map(|f| f.as_str().unwrap().to_string())
            .collect();
        assert_eq!(
            rfields,
            REVOCATION_NOTICE_FIELDS
                .iter()
                .map(|f| f.to_string())
                .collect::<Vec<_>>()
        );
        assert_eq!(v["revocationType"], REVOCATION_NOTICE_TYPE);

        for case in v["records"].as_array().unwrap() {
            let msg = parse_mailbox_message(case["wire"].as_str().unwrap())
                .unwrap_or_else(|e| panic!("record {}: {e}", case["name"]));
            match msg {
                MailboxMessage::Invitation(p) => {
                    assert_eq!(
                        serialize_invitation_payload(&p),
                        case["canonical"].as_str().unwrap(),
                        "record {}",
                        case["name"]
                    );
                }
                MailboxMessage::Revocation(_) => {
                    panic!("revocation record {}: not a revocation", case["name"])
                }
            }
        }

        for case in v["errors"].as_array().unwrap() {
            // Guards against a corrupted vector file (all wires are JSON,
            // except the deliberately-invalid-JSON case).
            if case["error"].as_str().unwrap() != "mailbox message: invalid JSON" {
                serde_json::from_str::<Value>(case["wire"].as_str().unwrap()).unwrap_or_else(|e| {
                    panic!("error case {}: wire is not valid JSON: {}", case["name"], e)
                });
            }
            assert_eq!(
                parse_mailbox_message(case["wire"].as_str().unwrap())
                    .unwrap_err()
                    .to_string(),
                case["error"].as_str().unwrap(),
                "error case {}",
                case["name"]
            );
        }

        for case in v["revocationRecords"].as_array().unwrap() {
            let msg = parse_mailbox_message(case["wire"].as_str().unwrap())
                .unwrap_or_else(|e| panic!("revocation record {}: {e}", case["name"]));
            match msg {
                MailboxMessage::Revocation(n) => {
                    assert_eq!(n.space_id, case["expected"]["space_id"].as_str().unwrap());
                    let epoch = case["expected"]["epoch"].as_i64();
                    assert_eq!(n.epoch, epoch, "revocation record {}", case["name"]);
                }
                MailboxMessage::Invitation(_) => {
                    panic!("revocation record {}: not a revocation", case["name"])
                }
            }
        }

        for case in v["revocationErrors"].as_array().unwrap() {
            assert_eq!(
                parse_mailbox_message(case["wire"].as_str().unwrap())
                    .unwrap_err()
                    .to_string(),
                case["error"].as_str().unwrap(),
                "revocation error case {}",
                case["name"]
            );
        }
    }
}
