//! The `__spaces` collection wire schema (frozen v1 contract, audit G7).
//!
//! `__spaces` is a library-managed collection in the personal space that
//! tracks the shared spaces a user belongs to, including the credentials
//! (space key, UCAN chain, root public key) needed to sync each space. The
//! collection syncs device-to-device inside the personal space — the server
//! never sees the plaintext — so the record shape is a purely client-side
//! wire contract. This module is the canonical definition of that contract:
//! the collection name, schema version, field names, and value sets.
//!
//! Conformance is pinned by `test-vectors/spaces-record.json` (generated by
//! `examples/generate_spaces_record_vectors.rs`), replayed by the Rust
//! conformance test, the node 1:1 mirror, and the real-wasm browser test.
//!
//! Counter fields (`epoch`, `epochAdvancedAt`, `membershipLogSeq`) accept
//! any JSON integer-valued number (incl. `1e3` / `1000.0` notation) up to
//! `MAX_COUNTER` (2^53 − 1, JS `Number.MAX_SAFE_INTEGER`) so Rust, the wasm
//! → JS boundary, and the node mirror all agree on acceptance. Only the
//! semantic error messages are part of the frozen contract; the
//! `malformed JSON: …` detail is engine-specific (serde vs. V8) and is not
//! vector-pinned.

use crate::membership::{MemberRole, MemberStatus};
use serde::{Deserialize, Serialize};
use serde_json::Value;
use thiserror::Error;

/// Collection name (frozen — the collection id in the personal-space db).
pub const SPACES_COLLECTION: &str = "__spaces";

/// Schema version (frozen v1).
pub const SPACES_SCHEMA_VERSION: u32 = 1;

/// Record field names in canonical order (frozen v1).
pub const SPACES_FIELDS: &[&str] = &[
    "spaceId",
    "name",
    "status",
    "role",
    "invitedBy",
    "spaceKey",
    "ucanChain",
    "rootPublicKey",
    "serverInvitationId",
    "epoch",
    "epochAdvancedAt",
    "members",
    "membershipLogSeq",
];

const REQUIRED_FIELDS: &[&str] = &[
    "spaceId",
    "name",
    "status",
    "role",
    "spaceKey",
    "ucanChain",
    "rootPublicKey",
    "epoch",
];

/// Frozen `status` values (wire strings).
pub const SPACES_STATUS_VALUES: &[&str] = &["invited", "active", "removed"];

/// Frozen role values (wire strings — the `MemberRole` set, shared between
/// the record's top-level `role` and each member entry).
pub const SPACES_ROLE_VALUES: &[&str] = &["admin", "write", "read"];

/// Frozen member `status` values (wire strings — the `MemberStatus` set).
pub const SPACES_MEMBER_STATUS_VALUES: &[&str] = &["joined", "pending", "declined", "revoked"];

/// Maximum counter value: JS `Number.MAX_SAFE_INTEGER` (2^53 − 1). Keeping
/// counters inside the exact-integer range of a JS `Number` is what makes
/// the acceptance rule identical across Rust, wasm→JS, and the node mirror.
const MAX_COUNTER: u64 = 9_007_199_254_740_991;

/// Membership status of the local user in a space.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum SpaceStatus {
    /// Invitation received but not yet accepted.
    Invited,
    /// Space is active; sync is running.
    Active,
    /// User was removed from the space (UCAN revoked).
    Removed,
}

impl SpaceStatus {
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Invited => "invited",
            Self::Active => "active",
            Self::Removed => "removed",
        }
    }
}

/// One cached member entry, as computed by the membership-log fold.
///
/// `Deserialize` is derived for symmetry with `Serialize` (used by
/// `serialize_spaces_record` / the wasm export) — the wire parser is
/// `parse_spaces_record`, not `serde_json::from_str::<SpaceMember>`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct SpaceMember {
    pub did: String,
    pub role: MemberRole,
    pub status: MemberStatus,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub handle: Option<String>,
}

/// One `__spaces` record: a shared space the user belongs to.
///
/// `Deserialize` is derived for symmetry with `Serialize` (used by
/// `serialize_spaces_record` / the wasm export) — the wire parser is
/// `parse_spaces_record`, not `serde_json::from_str::<SpacesRecord>`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct SpacesRecord {
    /// Shared space id (used for lookups — NOT the record id).
    pub space_id: String,
    /// Display name (from invitation or creation).
    pub name: String,
    /// Local user's membership status.
    pub status: SpaceStatus,
    /// Local user's role in the space.
    pub role: MemberRole,
    /// Username of the inviter (absent if the user created the space).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub invited_by: Option<String>,
    /// Base64-encoded AES-256 space key.
    pub space_key: String,
    /// UCAN JWT (leaf token with the proof chain embedded in `prf`).
    pub ucan_chain: String,
    /// Base64-encoded compressed P-256 public key of the space root.
    pub root_public_key: String,
    /// Server-side invitation id (deleted on accept/decline).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub server_invitation_id: Option<String>,
    /// Key epoch number — how many times the space key has been rotated.
    pub epoch: u64,
    /// Unix-ms timestamp the current epoch was established at (drives
    /// rotation scheduling).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub epoch_advanced_at: Option<u64>,
    /// Cached parsed member list from the membership log.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub members: Option<Vec<SpaceMember>>,
    /// Highest seq seen in the membership log (incremental-fetch cursor).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub membership_log_seq: Option<u64>,
}

#[derive(Debug, Error, PartialEq, Eq)]
pub enum SpacesRecordError {
    #[error("invalid __spaces record: {0}")]
    Invalid(String),
}

/// Parse a `__spaces` record from its wire JSON.
///
/// Validation is explicit (field-by-field, stable messages) so a second SDK
/// or the node mirror can reproduce it exactly:
/// - the record must be a JSON object with no fields beyond `SPACES_FIELDS`
/// - required fields must be present with the right types
/// - `status` / `role` / member roles / member statuses must be in the
///   frozen value sets
/// - `epoch` / `epochAdvancedAt` / `membershipLogSeq` must be
///   non-negative integers
pub fn parse_spaces_record(json: &str) -> Result<SpacesRecord, SpacesRecordError> {
    let v: Value = serde_json::from_str(json)
        .map_err(|e| SpacesRecordError::Invalid(format!("malformed JSON: {e}")))?;
    let obj = v
        .as_object()
        .ok_or_else(|| SpacesRecordError::Invalid("record must be a JSON object".into()))?;

    let unknown: Vec<&String> = obj
        .keys()
        .filter(|k| !SPACES_FIELDS.contains(&k.as_str()))
        .collect();
    let mut unknown_sorted = unknown;
    unknown_sorted.sort();
    if let Some(first) = unknown_sorted.first() {
        return Err(invalid(&format!("unknown field '{first}'")));
    }
    for field in REQUIRED_FIELDS.iter().copied() {
        if !obj.contains_key(field) {
            return Err(invalid(&format!("missing required field '{field}'")));
        }
    }

    let str_field = |name: &str| -> Result<String, SpacesRecordError> {
        let s = obj
            .get(name)
            .and_then(Value::as_str)
            .ok_or_else(|| invalid(&format!("field '{name}' must be a string")))?;
        Ok(s.to_string())
    };
    let opt_str_field = |name: &str| -> Option<String> {
        obj.get(name)
            .filter(|v| !v.is_null())
            .and_then(Value::as_str)
            .map(str::to_string)
    };
    let uint_field = |name: &str, required: bool| -> Result<Option<u64>, SpacesRecordError> {
        match obj.get(name) {
            None | Some(Value::Null) => {
                if required {
                    Err(invalid(&format!("missing required field '{name}'")))
                } else {
                    Ok(None)
                }
            }
            Some(Value::Number(n)) => {
                // Integer-valued numbers in any notation (u64 or f64-backed,
                // e.g. `1e3` / `1000.0`) are accepted, capped at MAX_COUNTER
                // so the JS mirror's `Number.isSafeInteger` check agrees.
                let v = n.as_u64().or_else(|| {
                    n.as_f64()
                        .filter(|f| f.is_finite() && f.fract() == 0.0 && *f >= 0.0)
                        .map(|f| f as u64)
                });
                match v.filter(|&u| u <= MAX_COUNTER) {
                    Some(u) => Ok(Some(u)),
                    None => Err(invalid(&format!(
                        "field '{name}' must be a non-negative integer"
                    ))),
                }
            }
            Some(_) => Err(invalid(&format!(
                "field '{name}' must be a non-negative integer"
            ))),
        }
    };

    let status = obj
        .get("status")
        .and_then(Value::as_str)
        .filter(|s| SPACES_STATUS_VALUES.contains(s))
        .map(|s| match s {
            "invited" => SpaceStatus::Invited,
            "active" => SpaceStatus::Active,
            _ => SpaceStatus::Removed,
        })
        .ok_or_else(|| invalid_enum("status", SPACES_STATUS_VALUES))?;

    let role = obj
        .get("role")
        .and_then(Value::as_str)
        .filter(|s| SPACES_ROLE_VALUES.contains(s))
        .map(|s| match s {
            "admin" => MemberRole::Admin,
            "write" => MemberRole::Write,
            _ => MemberRole::Read,
        })
        .ok_or_else(|| invalid_enum("role", SPACES_ROLE_VALUES))?;

    let mut record = SpacesRecord {
        space_id: str_field("spaceId")?,
        name: str_field("name")?,
        status,
        role,
        invited_by: opt_str_field("invitedBy"),
        space_key: str_field("spaceKey")?,
        ucan_chain: str_field("ucanChain")?,
        root_public_key: str_field("rootPublicKey")?,
        server_invitation_id: opt_str_field("serverInvitationId"),
        epoch: uint_field("epoch", true)?.expect("required field validated above"),
        epoch_advanced_at: uint_field("epochAdvancedAt", false)?,
        members: None,
        membership_log_seq: uint_field("membershipLogSeq", false)?,
    };

    if let Some(members) = obj.get("members").filter(|v| !v.is_null()) {
        let arr = members
            .as_array()
            .ok_or_else(|| invalid("field 'members' must be an array"))?;
        let mut parsed = Vec::with_capacity(arr.len());
        for (i, m) in arr.iter().enumerate() {
            let mobj = m
                .as_object()
                .ok_or_else(|| invalid(&format!("members[{i}] must be an object")))?;
            let mut member_unknown: Vec<&String> = mobj
                .keys()
                .filter(|k| !["did", "role", "status", "handle"].contains(&k.as_str()))
                .collect();
            member_unknown.sort();
            if let Some(key) = member_unknown.first() {
                return Err(invalid(&format!("members[{i}]: unknown field '{key}'")));
            }
            for field in ["did", "role", "status"] {
                if !mobj.contains_key(field) {
                    return Err(invalid(&format!(
                        "members[{i}]: missing required field '{field}'"
                    )));
                }
            }
            let did = mobj
                .get("did")
                .and_then(Value::as_str)
                .ok_or_else(|| invalid(&format!("members[{i}]: field 'did' must be a string")))?
                .to_string();
            let role = mobj
                .get("role")
                .and_then(Value::as_str)
                .filter(|s| SPACES_ROLE_VALUES.contains(s))
                .map(|s| match s {
                    "admin" => MemberRole::Admin,
                    "write" => MemberRole::Write,
                    _ => MemberRole::Read,
                })
                .ok_or_else(|| {
                    invalid(&format!(
                        "members[{i}]: {}",
                        enum_message("role", SPACES_ROLE_VALUES)
                    ))
                })?;
            let status = mobj
                .get("status")
                .and_then(Value::as_str)
                .filter(|s| SPACES_MEMBER_STATUS_VALUES.contains(s))
                .map(|s| match s {
                    "joined" => MemberStatus::Joined,
                    "pending" => MemberStatus::Pending,
                    "declined" => MemberStatus::Declined,
                    _ => MemberStatus::Revoked,
                })
                .ok_or_else(|| {
                    invalid(&format!(
                        "members[{i}]: {}",
                        enum_message("status", SPACES_MEMBER_STATUS_VALUES)
                    ))
                })?;
            let handle = mobj
                .get("handle")
                .filter(|v| !v.is_null())
                .and_then(Value::as_str)
                .map(str::to_string);
            parsed.push(SpaceMember {
                did,
                role,
                status,
                handle,
            });
        }
        record.members = Some(parsed);
    }

    Ok(record)
}

fn value_list(values: &[&str]) -> String {
    let n = values.len();
    let mut out = String::new();
    for (i, v) in values.iter().enumerate() {
        if i > 0 {
            out.push_str(if i == n - 1 { ", or " } else { ", " });
        }
        out.push_str(&format!("'{v}'"));
    }
    out
}

/// Bare enum error message (no record prefix) — e.g. for member entries
/// that prefix with `members[i]: `.
fn enum_message(field: &str, values: &[&str]) -> String {
    format!("field '{field}' must be {}", value_list(values))
}

fn invalid_enum(field: &str, values: &[&str]) -> SpacesRecordError {
    invalid(&enum_message(field, values))
}

fn invalid(msg: &str) -> SpacesRecordError {
    SpacesRecordError::Invalid(msg.to_string())
}

/// Serialize a record back to its wire JSON. Field order follows
/// `SPACES_FIELDS`; absent optionals are omitted.
pub fn serialize_spaces_record(record: &SpacesRecord) -> String {
    serde_json::to_string(record).expect("spaces record serializes")
}

#[cfg(test)]
mod tests {
    use super::*;

    fn base_record() -> SpacesRecord {
        SpacesRecord {
            space_id: "space-1".into(),
            name: "Team Space".into(),
            status: SpaceStatus::Active,
            role: MemberRole::Admin,
            invited_by: None,
            space_key: "YXV0aC1rZXk=".into(),
            ucan_chain: "eyJhbGciOiJlZDI1NTE5In0.".into(),
            root_public_key: "base64pubkey".into(),
            server_invitation_id: None,
            epoch: 3,
            epoch_advanced_at: Some(1_700_000_000_000),
            members: Some(vec![
                SpaceMember {
                    did: "did:key:z1".into(),
                    role: MemberRole::Admin,
                    status: MemberStatus::Joined,
                    handle: Some("alice@example.com".into()),
                },
                SpaceMember {
                    did: "did:key:z2".into(),
                    role: MemberRole::Write,
                    status: MemberStatus::Pending,
                    handle: None,
                },
            ]),
            membership_log_seq: Some(7),
        }
    }

    #[test]
    fn round_trip_preserves_record() {
        let record = base_record();
        let json = serialize_spaces_record(&record);
        assert_eq!(parse_spaces_record(&json).unwrap(), record);
    }

    #[test]
    fn round_trip_omits_absent_optionals() {
        let mut record = base_record();
        record.invited_by = None;
        record.server_invitation_id = None;
        record.epoch_advanced_at = None;
        record.members = None;
        record.membership_log_seq = None;
        let json = serialize_spaces_record(&record);
        let v: Value = serde_json::from_str(&json).unwrap();
        for key in [
            "invitedBy",
            "serverInvitationId",
            "epochAdvancedAt",
            "members",
            "membershipLogSeq",
        ] {
            assert!(v.get(key).is_none(), "{key} must be omitted");
        }
    }

    #[test]
    fn field_order_follows_canonical_order() {
        let json = serialize_spaces_record(&base_record());
        let order = top_level_key_order(&json);
        let expected: Vec<&str> = SPACES_FIELDS
            .iter()
            .copied()
            .filter(|f| !matches!(*f, "invitedBy" | "serverInvitationId"))
            .collect();
        assert_eq!(order, expected);
    }

    /// Key order as written in the raw JSON text (serde_json without
    /// `preserve_order` sorts parsed maps alphabetically, so the order must
    /// be read from the text itself).
    fn top_level_key_order(json: &str) -> Vec<String> {
        let chars: Vec<char> = json.chars().collect();
        let mut keys = Vec::new();
        let mut depth = 0i32;
        let mut i = 0usize;
        while i < chars.len() {
            let c = chars[i];
            if c == '"' {
                // Find the closing quote (handles escapes) and check
                // whether this string is a key: the next non-whitespace
                // char after it must be ':' at depth 1.
                let start = i;
                i += 1;
                while i < chars.len() {
                    if chars[i] == '\\' {
                        i += 2;
                        continue;
                    }
                    if chars[i] == '"' {
                        break;
                    }
                    i += 1;
                }
                let mut j = i + 1;
                while j < chars.len() && chars[j].is_whitespace() {
                    j += 1;
                }
                if depth == 1 && j < chars.len() && chars[j] == ':' {
                    let raw: String = chars[start + 1..i].iter().collect();
                    keys.push(raw);
                }
                i += 1;
                continue;
            }
            match c {
                '{' | '[' => depth += 1,
                '}' | ']' => depth -= 1,
                _ => {}
            }
            i += 1;
        }
        keys
    }

    #[test]
    fn rejects_unknown_fields() {
        let json = r#"{"spaceId":"s","name":"n","status":"active","role":"admin","spaceKey":"k","ucanChain":"u","rootPublicKey":"r","epoch":1,"metadataVersion":3}"#;
        assert_eq!(
            parse_spaces_record(json),
            Err(invalid("unknown field 'metadataVersion'"))
        );
    }

    #[test]
    fn rejects_missing_required_fields() {
        let json = r#"{"spaceId":"s","name":"n","status":"active","role":"admin","spaceKey":"k","ucanChain":"u","epoch":1}"#;
        assert_eq!(
            parse_spaces_record(json),
            Err(invalid("missing required field 'rootPublicKey'"))
        );
    }

    #[test]
    fn rejects_bad_enum_values() {
        let mk = |status: &str, role: &str| {
            format!(
                r#"{{"spaceId":"s","name":"n","status":"{status}","role":"{role}","spaceKey":"k","ucanChain":"u","rootPublicKey":"r","epoch":1}}"#
            )
        };
        assert_eq!(
            parse_spaces_record(&mk("pending", "admin")),
            Err(invalid(
                "field 'status' must be 'invited', 'active', or 'removed'"
            ))
        );
        assert_eq!(
            parse_spaces_record(&mk("active", "owner")),
            Err(invalid("field 'role' must be 'admin', 'write', or 'read'"))
        );
    }

    #[test]
    fn rejects_bad_member_entries() {
        let mk = |member: &str| {
            format!(
                r#"{{"spaceId":"s","name":"n","status":"active","role":"admin","spaceKey":"k","ucanChain":"u","rootPublicKey":"r","epoch":1,"members":[{member}]}}"#
            )
        };
        assert_eq!(
            parse_spaces_record(&mk(r#"{"role":"read","status":"joined"}"#)),
            Err(invalid("members[0]: missing required field 'did'"))
        );
        assert_eq!(
            parse_spaces_record(&mk(r#"{"did":"d","role":"owner","status":"joined"}"#)),
            Err(invalid(
                "members[0]: field 'role' must be 'admin', 'write', or 'read'"
            ))
        );
        assert_eq!(
            parse_spaces_record(&mk(r#"{"did":"d","role":"read","status":"active"}"#)),
            Err(invalid(
                "members[0]: field 'status' must be 'joined', 'pending', 'declined', or 'revoked'"
            ))
        );
    }

    #[test]
    fn counter_fields_accept_js_safe_integers() {
        let mk = |field: &str, value: &str| {
            format!(
                r#"{{"spaceId":"s","name":"n","status":"active","role":"admin","spaceKey":"k","ucanChain":"u","rootPublicKey":"r","epoch":1,"{field}":{value}}}"#
            )
        };
        // Integer-valued numbers in any notation are accepted (1e3 / 1000.0
        // == 1000)...
        assert_eq!(
            parse_spaces_record(&mk("epochAdvancedAt", "1e3"))
                .unwrap()
                .epoch_advanced_at,
            Some(1000)
        );
        assert_eq!(
            parse_spaces_record(&mk("membershipLogSeq", "1000.0"))
                .unwrap()
                .membership_log_seq,
            Some(1000)
        );
        // ...up to and including 2^53 - 1 (JS Number.MAX_SAFE_INTEGER)...
        assert_eq!(
            parse_spaces_record(&mk("epochAdvancedAt", "9007199254740991"))
                .unwrap()
                .epoch_advanced_at,
            Some(9_007_199_254_740_991)
        );
        // ...but not beyond it.
        assert_eq!(
            parse_spaces_record(&mk("epochAdvancedAt", "9007199254740992")),
            Err(invalid(
                "field 'epochAdvancedAt' must be a non-negative integer"
            ))
        );
    }

    #[test]
    fn rejects_non_integer_counters() {
        let mk = |field: &str, value: &str| {
            format!(
                r#"{{"spaceId":"s","name":"n","status":"active","role":"admin","spaceKey":"k","ucanChain":"u","rootPublicKey":"r","epoch":1,"{field}":{value}}}"#
            )
        };
        assert_eq!(
            parse_spaces_record(&mk("epoch", r#""1""#)),
            Err(invalid("field 'epoch' must be a non-negative integer"))
        );
        assert_eq!(
            parse_spaces_record(&mk("epoch", "-1")),
            Err(invalid("field 'epoch' must be a non-negative integer"))
        );
        assert_eq!(
            parse_spaces_record(&mk("epoch", "null")),
            Err(invalid("missing required field 'epoch'"))
        );
        assert_eq!(
            parse_spaces_record(&mk("membershipLogSeq", "1.5")),
            Err(invalid(
                "field 'membershipLogSeq' must be a non-negative integer"
            ))
        );
    }

    #[test]
    fn validation_precedence_matches_rust_order() {
        // Multi-fault inputs: the first error is determined by the Rust
        // check order (unknown fields alphabetically, required fields in
        // declaration order, enum values, then field types — with
        // membershipLogSeq before members).
        let multi = r#"{"spaceId":42,"name":"n","status":"paused","role":"admin","spaceKey":"k","ucanChain":"u","rootPublicKey":"r","epoch":1}"#;
        assert_eq!(
            parse_spaces_record(multi),
            Err(invalid(
                "field 'status' must be 'invited', 'active', or 'removed'"
            ))
        );

        let unknown_order = r#"{"zzz":1,"aaa":2,"spaceId":"s","name":"n","status":"active","role":"admin","spaceKey":"k","ucanChain":"u","rootPublicKey":"r","epoch":1}"#;
        assert_eq!(
            parse_spaces_record(unknown_order),
            Err(invalid("unknown field 'aaa'"))
        );

        let seq_before_members = r#"{"spaceId":"s","name":"n","status":"active","role":"admin","spaceKey":"k","ucanChain":"u","rootPublicKey":"r","epoch":1,"members":"x","membershipLogSeq":-1}"#;
        assert_eq!(
            parse_spaces_record(seq_before_members),
            Err(invalid(
                "field 'membershipLogSeq' must be a non-negative integer"
            ))
        );
    }

    #[test]
    fn key_order_is_not_significant() {
        let shuffled = r#"{"epoch":1,"rootPublicKey":"r","ucanChain":"u","spaceKey":"k","role":"admin","status":"active","name":"n","spaceId":"s"}"#;
        let parsed = parse_spaces_record(shuffled).unwrap();
        assert_eq!(parsed.space_id, "s");
        let canonical = serialize_spaces_record(&parsed);
        let v: Value = serde_json::from_str(&canonical).unwrap();
        assert!(v.get("spaceId").is_some());
    }

    #[test]
    fn conformance_vectors() {
        const VECTORS: &str = include_str!("../test-vectors/spaces-record.json");
        let file: Value = serde_json::from_str(VECTORS).expect("vector file parses");

        assert_eq!(file["collection"].as_str().unwrap(), SPACES_COLLECTION);
        assert_eq!(
            file["version"].as_u64().unwrap(),
            SPACES_SCHEMA_VERSION as u64
        );
        let fields: Vec<&str> = file["fields"]
            .as_array()
            .unwrap()
            .iter()
            .map(|v| v.as_str().unwrap())
            .collect();
        assert_eq!(fields, SPACES_FIELDS);

        let cases = file["records"].as_array().expect("records array");
        assert!(!cases.is_empty(), "vector file must not be empty");
        for case in cases {
            let name = case["name"].as_str().expect("case has a name");
            let parsed = parse_spaces_record(case["json"].as_str().unwrap())
                .unwrap_or_else(|e| panic!("vector '{name}': failed to parse: {e}"));
            assert_eq!(
                serialize_spaces_record(&parsed),
                case["canonical"].as_str().unwrap(),
                "vector '{name}': canonical serialization drift"
            );
        }

        let errors = file["errors"].as_array().expect("errors array");
        for case in errors {
            let name = case["name"].as_str().expect("case has a name");
            let got = parse_spaces_record(case["json"].as_str().unwrap())
                .expect_err("must fail")
                .to_string();
            assert_eq!(
                got,
                case["error"].as_str().unwrap(),
                "vector '{name}': error drift"
            );
        }
    }
}
